### ISSUE TITLE
Test it (and adapt, if needed) against Django 1.11.x

### ISSUE THREAD

**Issue by kplaube** [kplaube/django-simple-links#2]
We should test it against a newer Django version, and adapt it to work properly if needed.

**Comment by pixelexel** [comment]
Hi! I'd like to address this issue. This will be my first time handling an issue on Github so I'd like a little help. How exactly would one test this app? I'll install it in my Django project here https://github.com/pixelexel/Bloggr and see if it works as intended. Is that the correct approach?

**Comment by kplaube** [comment]
Hi! Thanks for helping me with this :)

Yes. This is one approach. You can also run the tests once it's been installed in your project (`python manage.py test`).

**Comment by pixelexel** [comment]
Hi!
So I installed simple links in my project and followed the getting started guide. From what I understand, simple links seems to work as expected on Django (1, 11, 4, u'final', 0).
I'm attaching a screenshot of the blog roll I created:
<img width="1680" alt="screen shot 2017-10-01 at 3 16 27 pm" src="https://user-images.githubusercontent.com/22503073/31053479-b53751da-a6bb-11e7-9e23-e9aca6156a1e.png">

Unfortunately, I haven't written any tests for my project yet so can't really run any.
However, Simple links seems like a great addition to my project!

**Comment by kplaube** [comment]
That's awesome, @pixelexel! Thank you so much! Could you please add this Django version to our `.travis.yml` file? https://github.com/kplaube/django-simple-links/blob/master/.travis.yml#L17

**Comment by pixelexel** [comment]
Thank you so much for helping me through this! 
I've updated `.travis.yml` to indicate support for DJANGO_VERSION=1.11.4 and created my first pull request!

**Comment by kplaube** [comment]
Excellent job, man! 👍

**Comment by pixelexel** [comment]
Thanks a lot! It feels great to contribute!
